[versions]
androidx-activity = "1.10.1"
androidx-core = "1.17.0"
androidx-benchmark = "1.3.4"
androidx-lifecycle = "2.9.2"
androidx-cardview = "1.0.0"
androidx-startup = "1.2.0"
androidx-swiperefreshlayout = "1.2.0-beta01"
androidx-webKit = "1.14.0"
androidx-window = "1.4.0"
androidx-browser = "1.9.0"
androidx-animationCore = "1.0.0"
androidx-datastore = "1.1.7"
androidx-draganddrop = "1.0.0"
androidx-concurrent = "1.3.0"
androidx-palette = "1.0.0"
androidx-appcompat = "1.7.1"
androidx-fragment = "1.8.9"
androidx-constraintlayout = "2.2.1"
androidx-navigation = "2.9.5"
androidx-room = "2.7.2"
androidx-work = "2.10.3"
androidx-camerax = "1.4.2"
androidx-asynclayoutinflater = "1.1.0"
espressoCore = "3.5.1"
junitVersion = "1.1.5"
material = "1.12.0"
preferenceVersion = "1.2.1"
recyclerview = "1.4.0"
asm = "9.8"
androidGradlePlugin = "8.9.1"
biometricKtx = "1.2.0-alpha05"
androidx-splashscreen = "1.0.1"
legacy = "1.0.0"
junit = "4.13.2"
kotlin = "2.1.10"
logkitMessenger = "1.7"
mailVersion = "1.4.5"
metricsPerformance = "1.0.0-beta02"
lottie = "6.6.6"
roundedProgressBar = "550a631d74"
runner = "1.5.2"
spotless = "7.2.1"
coroutines = "1.10.2"
benchmark = "1.4.0"
tracingKtx = "1.3.0"
koin-version = "4.1.0"
retrofit = "3.0.0"
activity-compose = "1.10.1"
compose-bom = "2025.08.00"
pagingVersion = "3.3.6"

#plugins
changelog = "2.2.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
android-benchmark = { id = "androidx.benchmark", version.ref = "benchmark" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version = "2.1.10-1.0.31" }
# ./gradlew generateChangelog 用于更新日志
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }


[libraries]
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "preferenceVersion" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "biometricKtx" }
androidx-tracing-ktx = { module = "androidx.tracing:tracing-ktx", version.ref = "tracingKtx" }
androidx-metrics-performance = { module = "androidx.metrics:metrics-performance", version.ref = "metricsPerformance" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "androidx-palette" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-recyclerview-selection = { module = "androidx.recyclerview:recyclerview-selection", version = "1.2.0" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
androidx-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-webKit = { module = "androidx.webkit:webkit", version.ref = "androidx-webKit" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-animationCore = { module = "androidx.core:core-animation", version.ref = "androidx-animationCore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-datastoreCore = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
androidx-dragAndDrop = { module = "androidx.draganddrop:draganddrop", version.ref = "androidx-draganddrop" }
androidx-concurrent = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "androidx-concurrent" }
androidx-legacy-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy" }
androidx-asynclayoutinflater = { module = "androidx.asynclayoutinflater:asynclayoutinflater", version.ref = "androidx-asynclayoutinflater" }
#navigation
androidx-navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }

# Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-page = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
# WorkManager
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "androidx-work" }
# Lifecycle
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }

# Paging
androidx-paging = { module = "androidx.paging:paging-runtime", version.ref = "pagingVersion" }

#cameraX
androidx-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "androidx-camerax" }
androidx-camera-video = { module = "androidx.camera:camera-video", version.ref = "androidx-camerax" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "androidx-camerax" }
androidx-camera-mlkit-vision = { module = "androidx.camera:camera-mlkit-vision", version.ref = "androidx-camerax" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "androidx-camerax" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "androidx-camerax" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "androidx-camerax" }

# Koin https://insert-koin.io/docs/setup/koin
koinBom = { module = "io.insert-koin:koin-bom", version.ref = "koin-version" }
koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin-version" }
koinWorkManager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin-version" }
koinAndroidCompat = { module = "io.insert-koin:koin-android-compat", version.ref = "koin-version" }
koinAndroidcompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-version" }
koinAndroidComposeNavigation = { module = "io.insert-koin:koin-androidx-navigation", version.ref = "koin-version" }

# Third
third-brv = { module = "com.github.CymChad:BaseRecyclerViewAdapterHelper", version = "3.0.11" }
third-gson = { module = "com.google.code.gson:gson", version = "2.13.1" }
third-glide = { module = "com.github.bumptech.glide:glide", version = "4.16.0" }
third-timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

# Retrofit2
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-sse = { module = "com.squareup.okhttp3:okhttp-sse", version = "5.1.0" }

# Coroutines
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# ASM
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }

#  Mine
shetj-activity = { module = "com.github.SheTieJun.androidx-ktx:activity", version = "1.1.0" }
shetj-qmui = { module = "com.github.SheTieJun:SimQUMI", version = "0.0.1" }
shetj-record-core = { module = "com.github.SheTieJun.Mp3Recorder:recorder-core", version = "1.9.3" }
shetj-record-sim = { module = "com.github.SheTieJun.Mp3Recorder:recorder-sim", version = "1.9.3" }
shetj-record-mix = { module = "com.github.SheTieJun.Mp3Recorder:recorder-mix", version = "1.9.3" }
logkit-messenger = { module = "com.github.SheTieJun.LogKit:logkit-messenger", version.ref = "logkitMessenger" }

javax-mail = { module = "javax.mail:mail", version.ref = "mailVersion" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
junit = { module = "junit:junit", version.ref = "junit" }
roundedProgressBar = { module = "com.github.SheTieJun:RoundedProgressBar", version.ref = "roundedProgressBar" }

## Compose
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-material-iconsCore = { group = "androidx.compose.material", name = "material-icons-core" }
compose-material-iconsExt = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material3-windowSize = { group = "androidx.compose.material3", name = "material3-window-size-class" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version = "1.1.1" }
compose-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.9.2" }
compose-paging = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingVersion" }